name: Release

on:
  push:
    tags:
      - "v*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/islandoftex/images/texlive:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: l3build ctan
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: fontaxes-ctan.zip
